# Generated by Django 5.2.12 on 2026-06-29 21:15

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_ecommerceintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_set',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='productcontentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['data_set'], name='catalog_document_data_set_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='document_chunk_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['data_set'], name='catalog_product_data_set_idx'),
        ),
        migrations.AddIndex(
            model_name='productcontentchunk',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='product_chunk_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
