# Generated by Django 5.2.12 on 2026-06-29 21:15

"""Force the shared 512 embedding dimension and add the data_set filter indexes.

YAZ-17: this migration used to also create the HNSW ANN indexes. Those were split
out into ``0016_hnsw_indexes_concurrent`` so they are built with PostgreSQL's
``CREATE INDEX CONCURRENTLY`` (no table-level lock on large chunk tables in
production). CONCURRENTLY cannot run inside a transaction, so it cannot live in
this otherwise-atomic migration.

The ``AlterField`` operations below rewrite both chunk ``embedding`` columns to
``vector(512)``. That ALTER fails on live data that already stores a different
dimension (``ERROR: expected 512 dimensions, not N``). Run the
``preflight_embedding_dimensions`` management command on each existing database
BEFORE deploying this migration; it reports (and, on blocking findings, exits
non-zero on) any stored vector or data set whose dimension is not 512. See the
pgvector migration runbook in ``docs/content/docs/management/vector-store.md``.
"""

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_ecommerceintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_set',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_set',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.dataset'),
        ),
        migrations.AlterField(
            model_name='productcontentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['data_set'], name='catalog_document_data_set_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['data_set'], name='catalog_product_data_set_idx'),
        ),
    ]
